;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-kill-sexp
        kill-region
        prelude-move-beginning-of-line
        python-indent-dedent-line-backspace
        smex
        sp--self-insert-command
        sp-backward-down-sexp
        ))

(setq mc/cmds-to-run-once
      '(
        ))
